# Generated by Django 5.1.2 on 2024-10-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
            ],
        ),
    ]
