# Generated by Django 5.1.2 on 2024-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='os_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
