# Generated by Django 5.1.2 on 2024-10-14 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_devicedata_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
